spring.application.name=clinica-api

# PostgreSQL
# Defina DB_PASSWORD no ambiente local antes de executar a aplicação.
spring.datasource.url=jdbc:postgresql://localhost:5433/clinica_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Server
server.port=8080
